; Bootstrap all needed packages (loads ACT-R, Cocoa framework, etc.)
(load (format nil "~a~a" (directory-namestring *load-truename*) "bootstrap.lisp"))

(ensure-defined
  (defun foo (a)
    4)
  (defun kdkd (b a)
    3)
  (defvar *foobar* 5)
  (defmacro lsls ()
    ())
  (defun aaaaaaaa (b)
    ())
  (defmacro aaaaa ()
    ()))
