
#|
(let ((string "hello")
      (size #@(100 100)))
  (sleep 5)
  (message-dialog string :title "Message" :size size :position #@(300 250))
  (print (get-front-window))
  (#/makeKeyWindow (cocoa-ref (get-front-window)))
  (#/isKeyWindow (cocoa-ref (get-front-window))))
(get-front-window)
(get-string-from-user "hello" :initial-string "j")
(message-dialog "hello" :title "Message" :size #@(100 100) :position #@(300 250))
(progn 
  (sleep 5) 
  (print (get-front-window))
  (print (#/isKeyWindow (cocoa-ref (get-front-window))))
  (print (#/isMainWindow (cocoa-ref (get-front-window)))))
(#/canBecomeKeyWindow (cocoa-ref *))
(#/makeKeyWindow (cocoa-ref *))
(#/enableKeyEquivalentForDefaultButtonCell (cocoa-ref (get-front-window)))
(#/defaultButtonCell (cocoa-ref *))
(cocoa-ref (view-named :db **))
(#/cell *)
(inspect *)
(setf *modal-dialog-ret* nil)
(consp t)
(objc:defmethod (#/drawRect: :void) ((self cocoa-drawing-view)
                                     (rect :<NSR>ect)))
(objc:defmethod (#/performKeyEquivalent: :boolean) ((self easygui::cocoa-window) the-event)
  (print "here")
  #$NO)
  ;(call-next-method the-event))
|#
