
(inspect *win*)
(view-mouse-position *win*)
(easygui::view-subviews (easygui::content-view *win*))
(easygui::view-subviews *win*)
(inspect (cocoa-ref (easygui::content-view *win*)))
(inspect (cocoa-ref (first (last (subviews *win*))))) 
(defmethod hit-test ((win window) x &optional (y nil))
  (destructuring-bind (x y) (canonicalize-point x y)
    (let ((view (#/hitTest:
                 (cocoa-ref (easygui:content-view *win*))
                 (ns:make-ns-point x y))))
      (print view))))
(#/performClick: (hit-test *win* 41 292) ccl:+null-ptr+)
(#/performClick: (hit-test *win* 252 191) ccl:+null-ptr+)
(setf *view* *)
(#/mouseDown: * nil)
(#/mouseUp: *view* nil)
(dotimes (i 20)
  (print (#/hitTest: 
          (cocoa-ref (easygui::content-view *win*))
          ;(cocoa-ref (first (last (subviews *win*))))
          (#/mouseLocationOutsideOfEventStream (cocoa-ref *win*))))
  (sleep 1))
(#/subviews (cocoa-ref (easygui::content-view *win*)))
(#/subviews (#/contentView (cocoa-ref *win*)))
